[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v18.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"
