version: '2'

vars:
  NAME: github-project-exporter
  VERSION: 0.3.0
  COMMIT: {sh: git rev-parse --verify HEAD}
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}"

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 go build .
  test:
    cmds:
      - go vet ./...
      - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} CGO_ENABLED=0 go build {{.BUILD_FLAGS}} .
      - tar -czf release/{{.NAME}}_{{.OS}}_{{.ARCH}}.tar.gz {{.NAME}}
      - rm -rf {{.NAME}}
  release:
    deps: [test]
    cmds:
      - mkdir -p release
      - task: package
        vars: {OS: "linux", ARCH: "amd64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm"}
      - task: package
        vars: {OS: "darwin", ARCH: "amd64"}
  github-release:
    deps: [release]
    cmds:
      - ghr v{{.VERSION}} release/
  clean:
    cmds:
      - rm -rf {{.NAME}} release cover.out
  build-container:
    cmds:
    - docker build --build-arg VERSION={{.VERSION}} --build-arg COMMIT={{.COMMIT}} -t summerwind/{{.NAME}}:latest -t summerwind/{{.NAME}}:{{.VERSION}} .
  push-container:
    cmds:
    - docker push summerwind/{{.NAME}}:latest
  push-release-container:
    cmds:
    - docker push summerwind/{{.NAME}}:{{.VERSION}}
